name: Actions - Fail
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Allowed as per policy
      - name: Harden-Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
    
      # Allowed as per policy
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      # Internal action - not allowed as per policy
      - name: Harden-Runner Fork
        uses: actions-security-demo/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # main
        with:
          egress-policy: audit
