name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This is using a compromised action.
      - name: Run a one-line script
        uses: step-security/dummy-compromised-action@main

      
