name: Pass
on:
  workflow_dispatch:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Allowed as per policy
      - name: Harden-Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
    
      # Allowed as per policy
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
