name: Secrets - Fail
on:
  push:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # Access to secrets in non-default branch not allowed as per policy.
    - env:
       VALUES: ${{ toJSON(secrets) }}
      run: sleep 20
    - name: Code Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
