name: Secrets - Fail
on:
  push:
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout code1
    - run: sleep 20
    - env:
       VALUES: ${{ toJSON(secrets) }}
      run: sleep 20
    - name: Code Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
