name: Test Fail with Composite Action

on:
  workflow_dispatch:

jobs:
  use-composite-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
          
      - uses: actions/checkout@v5
      # This action is a composite action that uses tj-actions/setup-bin which is not in allowed list
      - name: Run auto-doc
        uses: tj-actions/auto-doc@v3
